### ISSUE TITLE
Bug in remove punctuation

### ISSUE THREAD

**Issue by Dipti821** [PCON-Hacktoberfest-2022/Textutils#25] opened 2022-10-08 02:18 UTC
There is a bug in remove punctuation feature , it is removing ampersand symbol (&) while not removing question mark (?). Correct it.

**Comment by chikaldirick** [comment] 2022-10-08 14:26
I have pushed a tiny change to the remove punctuation regex within https://github.com/PCON-Hacktoberfest-2022/Textutils/pull/39
Could you please take a look when you have time

P.S. To set up project locally I had to fix a lot of errors caused by some errors in the code like:
- `capitalizeFirstWord` function does not have a closing curly brace (https://github.com/PCON-Hacktoberfest-2022/Textutils/blob/main/src/components/TextForm.js#L64) so the project can't be started.
- therefore some functions like `handleCopy` are duplicated (have two definitions) - this becomes an error when you resolve the 1st issue

**Comment by Dipti821** [comment] 2022-10-08 16:04
> I have pushed a tiny change to the remove punctuation regex within #39 Could you please take a look when you have time
> 
> P.S. To set up project locally I had to fix a lot of errors caused by some errors in the code like:
> 
> * `capitalizeFirstWord` function does not have a closing curly brace (https://github.com/PCON-Hacktoberfest-2022/Textutils/blob/main/src/components/TextForm.js#L64) so the project can't be started.
> * therefore some functions like `handleCopy` are duplicated (have two definitions) - this becomes an error when you resolve the 1st issue

Thanks for pointing out the error. I think one of the PR has resulted in this issue. Will review yours changes.

**Closed** 2022-10-08 16:29 UTC
Labels: bug, enhancement, hacktoberfest
